theme: jekyll-theme-minimal
title: Jeognjun Park
github:
  repository_url: "https://https://github.com/jeongjun-park/jeongjun-park.github.io"
description: <p><b>Communication Processor Software Development </b><br>Samsung LSI, Korea</p>
#logo: https://drive.google.com/uc?id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0
# logo: https://drive.google.com/uc?export=view&id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0/preview
logo: /assets/img/sunwook_2407.jpg
show_downloads: false
google_analytics:
